name: E2EScaleTrigger
on:
  schedule:
    - cron: '7 18 * * *'
  workflow_dispatch:
jobs:
  scale:
    if: github.repository == 'aws/karpenter' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/e2e.yaml
    with:
      suite: Scale
      event_name: ${{ github.event_name }}
      region: "us-west-2"
      enable_metrics: true
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}